### ISSUE TITLE
Switching handles on Windows

### ISSUE THREAD

**Issue by radoman93** [SolanaNFTCollector/Solana-Minting-Bot#20]
https://github.com/SolanaNFTCollector/Solana-Minting-Bot/blob/ecf8284c02feb696d0635f98aceac4b662db9fe3/magiceden.py#L97-L104

Switching to a different handle on windows is not correct. Should be - driver.switch_to.window(driver.window_handles[1]). Therefore the whole if-else is redundant.

**Comment by radoman93** [comment]
> https://github.com/SolanaNFTCollector/Solana-Minting-Bot/blob/ecf8284c02feb696d0635f98aceac4b662db9fe3/magiceden.py#L97-L104
> 
> Switching to a different handle on windows is not correct. Should be - driver.switch_to.window(driver.window_handles[1]). Therefore the whole if-else is redundant.

**Comment by SolanaNFTCollector** [comment]
Hello, thanks for the info, if possible could you fork, edit and create a merge request ? so that I can properly examine and see if it works ?
