### ISSUE TITLE
Change wallet

### ISSUE THREAD

**Issue by edson98lg** [SolanaNFTCollector/Solana-Minting-Bot#23]
Hi!
How to select another wallet from my phantom? I mean, I have 3 wallets with different balance and I'd like to select a specific one. :)
Thanks!

**Comment by SolanaNFTCollector** [comment]
For the moment your only option is tu use different wallets with different passphrases, for example launch program with wallet 1 and seed 1 then do the same with seed 2.
For now it is not supported using 2wallet from same seed. This will be later on but I haven't had time yet.

**Comment by edson98lg** [comment]
Thank so much!

**Comment by SolanaNFTCollector** [comment]
Made an update to the program if you want to check it out, updated phantom wallet extension is faster, especially with multiple wallets. could you try ?
