### ISSUE TITLE
Not add an seedphrase went launch

### ISSUE THREAD

**Issue by wangphu** [SolanaNFTCollector/Solana-Minting-Bot#30]
pls help me somtimes it not restore phantom wallet

**Comment by SolanaNFTCollector** [comment]
Hello, please can you give more details, for example a screenshot from the terminal ?

**Comment by wangphu** [comment]
![image](https://user-images.githubusercontent.com/82823264/165825636-81517c6b-9db5-4147-80f9-5f02c339c373.png)

**Comment by wangphu** [comment]
it stop when it come here

**Comment by SolanaNFTCollector** [comment]
Released a fix ff0ffde6ceb9741e0aecd57bf42d1b3be54927c6

**Comment by wangphu** [comment]
not fix sir

**Comment by wangphu** [comment]
if I open it for the first time, everything goes smoothly, but when I open it for the second time, I can't initialize the wallet phantom

**Comment by wangphu** [comment]
it not launch mutiple programs
