### ISSUE TITLE
Magic Eden/Phantom issue

### ISSUE THREAD

**Issue by jasontaliaferro** [SolanaNFTCollector/Solana-Minting-Bot#34]
The bot doesn't connect the wallet and after a minute the browser closes with an error in the command promt

![Screenshot_1](https://user-images.githubusercontent.com/104629895/165938933-f4cde613-a21c-4c74-8d85-f69bf6162317.png)
![Screenshot_2](https://user-images.githubusercontent.com/104629895/165938955-027c8cbb-002c-4b90-9cfb-7a9eaffd07ac.png)

**Comment by SolanaNFTCollector** [comment]
Please verify that you have donwloaded the latest version.

**Comment by jasontaliaferro** [comment]
Yes, I'm using the latest version

**Comment by SolanaNFTCollector** [comment]
Please try using this then [link](https://github.com/SolanaNFTCollector/Solana-Minting-Bot/releases/tag/v3)

**Comment by tomas938** [comment]
is it safe ?

**Comment by jasontaliaferro** [comment]
> 


> Please try using this then [link](https://github.com/SolanaNFTCollector/Solana-Minting-Bot/releases/tag/v3)

This one doesn't restore phantom wallet by using recovery phrase

**Comment by SolanaNFTCollector** [comment]
I will look into it please give me time.

**Comment by SaadMahboubi** [comment]
Hello guys, i have the same issus, there is any solution ?

**Comment by SolanaNFTCollector** [comment]
Will give a solution this weekend

**Comment by SolanaNFTCollector** [comment]
Fixed  : 2cafb0078bff2a8d723886e5719cc0803b6a664c
