### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by bruno353** [SolanaNFTCollector/Solana-Minting-Bot#36]
![image](https://user-images.githubusercontent.com/82957886/166082140-fba0ed5b-48fb-4961-9b78-b1b6961c1cf0.png)

**Comment by SolanaNFTCollector** [comment]
Will release a fix this weekend

**Comment by SolanaNFTCollector** [comment]
Please give more information on how to recreate.

**Comment by SolanaNFTCollector** [comment]
Fixed in 2cafb0078bff2a8d723886e5719cc0803b6a664c
