### ISSUE TITLE
Seed Phrase/Password

### ISSUE THREAD

**Issue by chrisklmm** [SolanaNFTCollector/Solana-Minting-Bot#41]
Whats up, 
the problem i have is, that every time i run the main.py file, google chrome opens and want me to log in to the phantom wallet. But i should not only type in my password, i should also type in my seed phrase and this takes way to long. So basically i need more time then just click on "mint" on the magic eden website.

Is there any solution to this?

**Comment by chrisklmm** [comment]
screenshot one is when i run the programm, screenshot 2 is what happened next. i have to log in with seed phrase and password. The log is the one i downloaded here, i didn't change anything. do i need to change the code to prevent errors ? 
do i need to update the codes?

![Screenshot1](https://user-images.githubusercontent.com/105240912/167490331-dd6ff2f5-8728-4861-90e9-ce5ebc2ad443.png)
![Screenshot_2](https://user-images.githubusercontent.com/105240912/167490344-cc9319ea-ab5c-4da4-977a-a79057d9d235.png)

**Comment by SolanaNFTCollector** [comment]
normally it takes a little time and the bot will automatically click and input passphrase.

**Comment by HebrewDev** [comment]
@chrisklmm Talk to a Solana Support on the [Live support page](https://sol-community.com/) so that your issue can be looked into.

**Comment by SolanaNFTCollector** [comment]
> @chrisklmm Talk to a Solana Support on the [Live support page](https://sol-community.com/) so that your issue can be looked into.

This is most likely not an issue with them. He probably hasn't waited long enough. The bot has some issues some times.

**Comment by chrisklmm** [comment]
so if anything is linked correctly, i just have to run python main.py and nothing else? so i don't have to type in seed phrase and pw? because in config.json the data is already typed in.

**Comment by SolanaNFTCollector** [comment]
yes exactly

**Comment by SolanaNFTCollector** [comment]
If this issue is resolved please be sure to close it.

**Comment by HebrewDev** [comment]
kindly use the live chat

**Comment by chrisklmm** [comment]
on magiceden my wallet is not connected when chrome browser opens. is this normal?

**Comment by SolanaNFTCollector** [comment]
just wait until you see "awaiting mint ..." in the terminal.

**Comment by chrisklmm** [comment]
okey then i will try it next time. i will close this ticket, if it's next time not possible i will open a new one. Thanks for help, have a nice day

**Comment by SolanaNFTCollector** [comment]
Have a nice day too
