### ISSUE TITLE
it doesn't login itself I just keep waiting until it crashes

### ISSUE THREAD

**Issue by weaksou** [SolanaNFTCollector/Solana-Minting-Bot#43]
===== WebDriver manager ======
Current google-chrome version is 101.0.4951
Get LATEST chromedriver version for 101.0.4951 google-chrome
Driver [C:\Users\adil\.wdm\drivers\chromedriver\win32\101.0.4951.41\chromedriver.exe] found in cache
Assertion - successfully found chrome driver
Status - Initializing wallet
Event - switch window
Traceback (most recent call last):
  File "C:\Users\adil\Desktop\Solana-Minting-Bot-main\main.py", line 26, in <module>
    magiceden.mint(config, isWindows)
  File "C:\Users\adil\Desktop\Solana-Minting-Bot-main\magiceden.py", line 149, in mint
    main_window = initWallet()
  File "C:\Users\adil\Desktop\Solana-Minting-Bot-main\magiceden.py", line 27, in initWallet
    WebDriverWait(driver, 60).until(EC.presence_of_element_located(
  File "C:\Users\adil\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        Ordinal0 [0x0058B8F3+2406643]
        Ordinal0 [0x0051AF31+1945393]
        Ordinal0 [0x0040C748+837448]
        Ordinal0 [0x004392E0+1020640]
        Ordinal0 [0x0043957B+1021307]
        Ordinal0 [0x00466372+1205106]
        Ordinal0 [0x004542C4+1131204]
        Ordinal0 [0x00464682+1197698]
        Ordinal0 [0x00454096+1130646]
        Ordinal0 [0x0042E636+976438]
        Ordinal0 [0x0042F546+980294]
        GetHandleVerifier [0x007F9612+2498066]
        GetHandleVerifier [0x007EC920+2445600]
        GetHandleVerifier [0x00624F2A+579370]
        GetHandleVerifier [0x00623D36+574774]
        Ordinal0 [0x00521C0B+1973259]
        Ordinal0 [0x00526688+1992328]
        Ordinal0 [0x00526775+1992565]
        Ordinal0 [0x0052F8D1+2029777]
        BaseThreadInitThunk [0x75F8FA29+25]
        RtlGetAppContainerNamedObjectPath [0x772F7A7E+286]
        RtlGetAppContainerNamedObjectPath [0x772F7A4E+238]

**Comment by SolanaNFTCollector** [comment]
will be fixing this today

**Comment by SolanaNFTCollector** [comment]
Fix is done, It happens sometimes just re-run de python main.py and une latest version.
5af21fe9d854a988696448dd413739f05d24e0b0

**Comment by weaksou** [comment]
thank you <3
