### ISSUE TITLE
window waiting for init wallet until crashing 

### ISSUE THREAD

**Issue by Enjules** [SolanaNFTCollector/Solana-Minting-Bot#46]
====== WebDriver manager ======
Found magiceden.io link
Bot started
OS : Windows
Current google-chrome version is 101.0.4951
Get LATEST chromedriver version for 101.0.4951 google-chrome
Driver [C:\Users\Enjules Maggle\.wdm\drivers\chromedriver\win32\101.0.4951.41\chromedriver.exe] found in cache
Assertion - successfully found chrome driver
Status - Initializing wallet
Event - switch window
Traceback (most recent call last):
  File "G:\Workspace\Experimentations\PYTHON\08_minting_bot\Solana-Minting-Bot\main.py", line 26, in <module>
    magiceden.mint(config, isWindows)
  File "G:\Workspace\Experimentations\PYTHON\08_minting_bot\Solana-Minting-Bot\magiceden.py", line 144, in mint
    initWallet()
  File "G:\Workspace\Experimentations\PYTHON\08_minting_bot\Solana-Minting-Bot\magiceden.py", line 25, in initWallet
    WebDriverWait(driver, 60).until(EC.presence_of_element_located(
  File "G:\Workspace\Experimentations\PYTHON\08_minting_bot\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
Backtrace:
	Ordinal0 [0x0101B8F3+2406643]
	Ordinal0 [0x00FAAF31+1945393]
	Ordinal0 [0x00E9C748+837448]
	Ordinal0 [0x00EC92E0+1020640]
	Ordinal0 [0x00EC957B+1021307]
	Ordinal0 [0x00EF6372+1205106]
	Ordinal0 [0x00EE42C4+1131204]
	Ordinal0 [0x00EF4682+1197698]
	Ordinal0 [0x00EE4096+1130646]
	Ordinal0 [0x00EBE636+976438]
	Ordinal0 [0x00EBF546+980294]
	GetHandleVerifier [0x01289612+2498066]
	GetHandleVerifier [0x0127C920+2445600]
	GetHandleVerifier [0x010B4F2A+579370]
	GetHandleVerifier [0x010B3D36+574774]
	Ordinal0 [0x00FB1C0B+1973259]
	Ordinal0 [0x00FB6688+1992328]
	Ordinal0 [0x00FB6775+1992565]
	Ordinal0 [0x00FBF8D1+2029777]
	BaseThreadInitThunk [0x775DFA29+25]
	RtlGetAppContainerNamedObjectPath [0x77E87A7E+286]
	RtlGetAppContainerNamedObjectPath [0x77E87A4E+238]

Process finished with exit code 1

**Comment by SolanaNFTHolder** [comment]
Maybe it`s scam?)

**Comment by paschaldev** [comment]
Crashes on MAC as well

<img width="888" alt="Screen Shot 2022-05-24 at 4 59 43 PM" src="https://user-images.githubusercontent.com/13323281/170080709-07c13b22-735d-4de6-8539-cb39417313dd.png">

**Comment by SolanaNFTCollector** [comment]
Will look now.

**Comment by SolanaNFTCollector** [comment]
Hello please restart the program and be sure to: 
- check to have a stable connection
- do not touch anything, dont click on any buttons.

**Comment by SolanaNFTCollector** [comment]
Will close, if any problem reopen please :)
