### ISSUE TITLE
Automatic mint

### ISSUE THREAD

**Issue by Hutsnabil** [SolanaNFTCollector/Solana-Minting-Bot#54]
Hey man, 
Thank you for the bot.
i do have a question tho, i started the bot and get this message

Status - Selecting wallet on ME
Status - Finished Selecting Wallet on ME
Status - Waiting for Mint, maximum time wait is 24h, after that please restart bot

Is it gonna mint by itself now and do I have to do anything now?

Thank you Nabil.

**Comment by SolanaNFTCollector** [comment]
Nope, will mint completely auto, of course I cant guarantee it to you but il will try minting when it's available.

**Comment by Hutsnabil** [comment]
Yeah ofcourse not guaranteed, thank you so much
