### ISSUE TITLE
Multiple Wallets

### ISSUE THREAD

**Issue by dan-ielc** [SolanaNFTCollector/Solana-Minting-Bot#56]
How would you use multiple wallets to increase the minting chance, do you download the software twice in two different folders?

**Comment by SolanaNFTCollector** [comment]
yes exactly, download once, then make a duplicate of folder, dont forget to put different wallet in each config file.

**Comment by SolanaNFTCollector** [comment]
To increase chance, try using a good connection and do not download anything in the meantime.

**Comment by dan-ielc** [comment]
Alright thanks.
