### ISSUE TITLE
selenium.common.exceptions.TimeoutException: Message:  Stacktrace:

### ISSUE THREAD

**Issue by omitao** [SolanaNFTCollector/Solana-Minting-Bot#60]
I Follow the step.but didnt work..

File "/Users/wangtao/Downloads/Solana-Minting-Bot-main/magiceden.py", line 150, in mint
    selectWallet()
  File "/Users/wangtao/Downloads/Solana-Minting-Bot-main/magiceden.py", line 63, in selectWallet
    WebDriverWait(driver, 60).until(EC.presence_of_element_located(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/support/wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
0   chromedriver                        0x0000000102c42ae0 chromedriver + 3828448
1   chromedriver                        0x0000000102bd7f1c chromedriver + 3391260
2   chromedriver                        0x00000001028d0fcc chromedriver + 217036
3   chromedriver                        0x0000000102900b7c chromedriver + 412540
4   chromedriver                        0x0000000102929b2c chromedriver + 580396
5   chromedriver                        0x00000001028f6010 chromedriver + 368656
6   chromedriver                        0x0000000102c1839c chromedriver + 3654556
7   chromedriver                        0x0000000102c1bc4c chromedriver + 3669068
8   chromedriver                        0x0000000102c2014c chromedriver + 3686732
9   chromedriver                        0x0000000102c1c654 chromedriver + 3671636
10  chromedriver                        0x0000000102bfab40 chromedriver + 3533632
11  chromedriver                        0x0000000102c34414 chromedriver + 3769364
12  chromedriver                        0x0000000102c34578 chromedriver + 3769720
13  chromedriver                        0x0000000102c490f0 chromedriver + 3854576
14  libsystem_pthread.dylib             0x00000001a43f826c _pthread_start + 148
15  libsystem_pthread.dylib             0x00000001a43f308c thread_start + 8

**Comment by SolanaNFTCollector** [comment]
hello, I will look into this today.

**Comment by SolanaNFTCollector** [comment]
Fixed
8a5b018e0c3a40b43874b4f1e14760fa47e46b55
