### ISSUE TITLE
Pip not recognised

### ISSUE THREAD

**Issue by suckthebergg** [SolanaNFTCollector/Solana-Minting-Bot#64]
Says '''pip' is not recognized as an internal or external command, operable program or batch file.'' in cmd prompt when i type pip install selenium requests webdriver-manager''

**Comment by SolanaNFTCollector** [comment]
hello, please verify that python path was added to your environment variables, you can find alot of tutorials for that on google.

**Comment by suckthebergg** [comment]
thank you
